name = "websocket-template"
type = "javascript"
account_id = "705cc338575f6bc5c2059ad0b922312f"
workers_dev = true
compatibility_date = "2022-02-20"

[build.upload]
format = "modules"
dir = "./src"
main = "./index.mjs"

[durable_objects]
bindings = [
  { name = "router", class_name = "Router" }
]